import type { BuildingDef, TechDef } from './types';

export const BUILDINGS: BuildingDef[] = [
  // ---- Industry ----------------------------------------------------------
  {
    id: 'foundry',
    name: 'Ironworks Combine',
    blurb: 'Blast furnaces running three shifts. The unglamorous backbone of everything else.',
    category: 'industry',
    baseCost: 25,
    growth: 1.16,
    effects: { prodFlat: 0.6 },
  },
  {
    id: 'assembly',
    name: 'Continuous Assembly Line',
    blurb: 'Standardised parts moving past standing workers. Lifts output across the whole economy.',
    category: 'industry',
    baseCost: 220,
    growth: 1.19,
    requires: 'tooling',
    effects: { prodMult: 0.05 },
  },
  {
    id: 'refinery',
    name: 'Synthetic Fuels Refinery',
    blurb: 'Turns whatever you have into whatever your tanks drink.',
    category: 'industry',
    baseCost: 1400,
    growth: 1.18,
    requires: 'petrochem',
    effects: { prodFlat: 7, convMult: 0.05 },
  },
  {
    id: 'orbital',
    name: 'Orbital Solar Array',
    blurb: 'Power beamed down from geostationary mirrors. Weather is no longer a factor.',
    category: 'industry',
    baseCost: 40000,
    growth: 1.2,
    requires: 'orbital_mfg',
    effects: { prodFlat: 140, prodMult: 0.04 },
  },

  // ---- Science -----------------------------------------------------------
  {
    id: 'institute',
    name: 'Institute of Applied Sciences',
    blurb: 'Somewhere between a university and a workshop, and better than either.',
    category: 'science',
    baseCost: 40,
    growth: 1.17,
    effects: { resFlat: 0.25 },
  },
  {
    id: 'datagrid',
    name: 'National Data Grid',
    blurb: 'Every laboratory in the country reading from the same ledger.',
    category: 'science',
    baseCost: 600,
    growth: 1.19,
    requires: 'computation',
    effects: { resMult: 0.07 },
  },
  {
    id: 'thinktank',
    name: 'Deep Analysis Array',
    blurb: 'Machines that propose the experiments, then run them overnight.',
    category: 'science',
    baseCost: 22000,
    growth: 1.2,
    requires: 'agi',
    effects: { resFlat: 55, resMult: 0.05 },
  },

  // ---- Military ----------------------------------------------------------
  {
    id: 'conscription',
    name: 'Conscription Bureau',
    blurb: 'Files, medical boards and letters nobody wants. Raises the ceiling on your standing army.',
    category: 'military',
    baseCost: 60,
    growth: 1.16,
    effects: { manpowerFlat: 8, manpowerMult: 0.02 },
  },
  {
    id: 'depot',
    name: 'Forward Logistics Depot',
    blurb: 'Fuel, boots and bullets stacked where they will be needed. Every industry point buys more army.',
    category: 'military',
    baseCost: 150,
    growth: 1.18,
    effects: { convMult: 0.08 },
  },
  {
    id: 'academy',
    name: 'General Staff Academy',
    blurb: 'Officers who have already lost this war on paper, twice, and learned from it.',
    category: 'military',
    baseCost: 320,
    growth: 1.19,
    effects: { effMult: 0.05, lossRed: 0.01 },
  },
  {
    id: 'arsenal',
    name: 'Strategic Arsenal',
    blurb: 'Hardened silos and a very short chain of command. Nobody wants to test it.',
    category: 'military',
    baseCost: 9000,
    growth: 1.21,
    requires: 'deterrence',
    effects: { effMult: 0.16, lossRed: 0.02 },
  },

  // ---- Civic -------------------------------------------------------------
  {
    id: 'morale',
    name: 'Ministry of Public Morale',
    blurb: 'Posters, parades and a very confident radio voice. People have more children.',
    category: 'civic',
    baseCost: 90,
    growth: 1.17,
    effects: { popMult: 0.1 },
  },
  {
    id: 'prefecture',
    name: 'Occupation Prefecture',
    blurb: 'Civil administrators sent to make the new border feel like an old one.',
    category: 'civic',
    baseCost: 400,
    growth: 1.18,
    requires: 'administration',
    effects: { assimMult: 0.18 },
  },
  {
    id: 'gendarmerie',
    name: 'Gendarmerie Corps',
    blurb: 'Police who are not quite soldiers, freeing soldiers to be soldiers.',
    category: 'civic',
    baseCost: 500,
    growth: 1.17,
    requires: 'pacification',
    effects: { garrisonRed: 0.05 },
  },
  {
    id: 'academy_civil',
    name: 'Language & Census Office',
    blurb: 'One tongue, one register, one taxpayer roll. Conquests come to heel faster.',
    category: 'civic',
    baseCost: 2600,
    growth: 1.19,
    requires: 'assimilation',
    effects: { assimMult: 0.3, popMult: 0.08 },
  },
];

export const TECHS: TechDef[] = [
  // ---- Tier 1 ------------------------------------------------------------
  {
    id: 'tooling',
    name: 'Standardised Tooling',
    blurb: 'Interchangeable parts. Cheap to adopt, and it makes everything after it cheaper.',
    category: 'industry',
    cost: 20,
    requires: [],
    effects: { costRed: 0.08, prodMult: 0.05 },
    unlocks: ['assembly'],
  },
  {
    id: 'agronomy',
    name: 'Mechanised Agronomy',
    blurb: 'Fewer farmers feeding more people. The surplus walks into your factories.',
    category: 'civic',
    cost: 30,
    requires: [],
    effects: { popMult: 0.2, prodMult: 0.05 },
  },
  {
    id: 'schooling',
    name: 'Universal Schooling',
    blurb: 'A literate population is a compounding asset. Slow, then sudden.',
    category: 'science',
    cost: 45,
    requires: [],
    effects: { resMult: 0.15 },
  },
  {
    id: 'radio',
    name: 'Field Radio Doctrine',
    blurb: 'Orders that arrive while they still matter.',
    category: 'military',
    cost: 60,
    requires: [],
    effects: { effMult: 0.12, lossRed: 0.05 },
  },

  // ---- Tier 2 ------------------------------------------------------------
  {
    id: 'computation',
    name: 'Computational Modelling',
    blurb: 'Simulate it before you build it. Halves the number of expensive mistakes.',
    category: 'science',
    cost: 200,
    requires: ['schooling'],
    effects: { resMult: 0.15 },
    unlocks: ['datagrid'],
  },
  {
    id: 'petrochem',
    name: 'Petrochemical Cracking',
    blurb: 'Long hydrocarbons broken into useful short ones. Plastics, propellant, profit.',
    category: 'industry',
    cost: 260,
    requires: ['tooling'],
    effects: { prodMult: 0.12 },
    unlocks: ['refinery'],
  },
  {
    id: 'administration',
    name: 'Colonial Administration',
    blurb: 'A filing system for other people’s countries.',
    category: 'civic',
    cost: 180,
    requires: ['agronomy'],
    effects: { assimMult: 0.25 },
    unlocks: ['prefecture'],
  },
  {
    id: 'pacification',
    name: 'Pacification Doctrine',
    blurb:
      'Curfews, local auxiliaries and a light touch in public. Fewer troops needed to hold a hostile province.',
    category: 'civic',
    cost: 300,
    requires: ['administration'],
    effects: { garrisonRed: 0.2 },
    unlocks: ['gendarmerie'],
  },
  {
    id: 'combined_arms',
    name: 'Combined Arms Doctrine',
    blurb: 'Armour, infantry and air answering to one timetable.',
    category: 'military',
    cost: 320,
    requires: ['radio'],
    effects: { effMult: 0.25, lossRed: 0.05 },
  },
  {
    id: 'mobilisation',
    name: 'National Mobilisation Act',
    blurb: 'The reserve lists stop being theoretical.',
    category: 'military',
    cost: 240,
    requires: ['radio'],
    effects: { manpowerMult: 0.35 },
  },

  // ---- Tier 3 ------------------------------------------------------------
  {
    id: 'automation',
    name: 'Industrial Automation',
    blurb: 'The night shift is now a maintenance rota.',
    category: 'industry',
    cost: 1200,
    requires: ['petrochem', 'computation'],
    effects: { prodMult: 0.3, costRed: 0.07 },
  },
  {
    id: 'total_war',
    name: 'Total War Economy',
    blurb: 'Consumer goods are rationed. Everything else is a munitions plant.',
    category: 'military',
    cost: 1500,
    requires: ['mobilisation', 'petrochem'],
    effects: { convMult: 0.6, manpowerMult: 0.25, popMult: -0.1 },
  },
  {
    id: 'assimilation',
    name: 'Cultural Assimilation',
    blurb: 'Two generations and the border is a line in a history book.',
    category: 'civic',
    cost: 1100,
    requires: ['administration', 'schooling'],
    effects: { assimMult: 0.6 },
    unlocks: ['academy_civil'],
  },
  {
    id: 'deterrence',
    name: 'Strategic Deterrence',
    blurb: 'The most useful weapons are the ones you never fire.',
    category: 'military',
    cost: 2600,
    requires: ['combined_arms', 'automation'],
    effects: { effMult: 0.35, lossRed: 0.08 },
    unlocks: ['arsenal'],
  },
  {
    id: 'logistics',
    name: 'Containerised Logistics',
    blurb: 'One box, every vehicle, every port. Quietly the most important invention here.',
    category: 'industry',
    cost: 2200,
    requires: ['automation'],
    effects: { prodMult: 0.25, convMult: 0.3 },
  },

  // ---- Tier 4 ------------------------------------------------------------
  {
    id: 'agi',
    name: 'General Machine Intelligence',
    blurb: 'Research that continues while the researchers sleep.',
    category: 'science',
    cost: 12000,
    requires: ['computation', 'automation'],
    effects: { resMult: 0.6, prodMult: 0.15 },
    unlocks: ['thinktank'],
  },
  {
    id: 'orbital_mfg',
    name: 'Orbital Manufacturing',
    blurb: 'Vacuum and free fall turn out to be excellent industrial conditions.',
    category: 'industry',
    cost: 18000,
    requires: ['logistics', 'agi'],
    effects: { prodMult: 0.4 },
    unlocks: ['orbital'],
  },
  {
    id: 'precision',
    name: 'Precision Munitions',
    blurb: 'One target, one round. Your casualty lists get much shorter.',
    category: 'military',
    cost: 15000,
    requires: ['deterrence', 'agi'],
    effects: { effMult: 0.6, lossRed: 0.15 },
  },
  {
    id: 'hegemony',
    name: 'Global Hegemony',
    blurb: 'The world’s institutions now run on your calendar. Everything gets easier.',
    category: 'civic',
    cost: 60000,
    requires: ['precision', 'orbital_mfg', 'assimilation'],
    effects: {
      prodMult: 0.5,
      resMult: 0.5,
      effMult: 0.5,
      manpowerMult: 0.5,
      assimMult: 1,
      garrisonRed: 0.3,
    },
  },
];

export const BUILDING_BY_ID = new Map(BUILDINGS.map((b) => [b.id, b]));
export const TECH_BY_ID = new Map(TECHS.map((t) => [t.id, t]));

export const CATEGORY_LABEL: Record<string, string> = {
  industry: 'Industry',
  science: 'Science',
  military: 'Military',
  civic: 'Civic',
};
